export default {
        login: 'CateringSystem1.0/recruitment/catering/login.do?method=login',
        dingni: 'CateringSystem1.0/recruitment/catering/qryDeskArea.do?method=login',
        table: 'CateringSystem1.0/recruitment/catering/qryDeskTopList.do?method=login',
        menuclass: 'CateringSystem1.0/recruitment/catering/qryMenuClassList.do?method=login',
        menu: "CateringSystem1.0/recruitment/catering/qryMenuListByDesk.do?method=login",
        addmenu: 'CateringSystem1.0/recruitment/catering/orderMenu.do?method=login',
        submenu: 'CateringSystem1.0/recruitment/catering/cancleOrderMenu.do?method=login',
        addjiu: 'CateringSystem1.0/recruitment/catering/accumlateMenu.do?method=login',
        subjiu: 'CateringSystem1.0/recruitment/catering/subAccumlateMenu.do?method=login',
        xiadan: 'CateringSystem1.0/recruitment/catering/qryOrderMenuList.do?method=login',
        empty: 'CateringSystem1.0/recruitment/catering/emptyOrderMenuByDeskId.do?method=login',
        beizhu: 'CateringSystem1.0/recruitment/catering/qryMenuItemSpecialRequest.do?method=login',
        ksxd: 'CateringSystem1.0/recruitment/catering/postOrderMenu.do?method=login',
        addbeizhu: 'CateringSystem1.0/recruitment/catering/addMenuMemo.do?method=login',
        txbeizhu: 'CateringSystem1.0/recruitment/catering/qryMenuMemoList.do?method=login',
        menuzt: 'CateringSystem1.0/recruitment/catering/changeOrderStatus.do?method=login',
        cxipdata: 'CateringSystem1.0/recruitment/catering/qryCostomerInfoList.do?method=login',
        addipdata: 'CateringSystem1.0/recruitment/catering/addCustomerInfo.do?method=login'
}